(function () {
    'use strict';

    var app = angular.module('fvApp');

    /**
     * @ngdoc object
     * @name fvApp.constant:EVENTS
     * @description
     * # EVENTS
     * All the supported $rootScope events.
     */
    app.constant('EVENTS', {
        profile: {
            fetchProfileFailed: 'fetch-profile-failed',
            profileImageUpdated: 'profile-image-updated'
        },
        user: {
            createSuccess: 'user-creation-success',
            createFailed: 'user-creation-failed',
            updateSuccess: 'user-update-success',
            updateFailed: 'user-update-failed',
        },
        auth: {
            registrationSuccess: 'auth-registration-success',
            registrationFailed: 'auth-registration-failed',
            loginSuccess: 'auth-login-success',
            loginFailed: 'auth-login-failed',
            logoutSuccess: 'auth-logout-success',
            sessionTimeout: 'auth-session-timeout',
            notAuthenticated: 'auth-not-authenticated',
            notAuthorized: 'auth-not-authorized'
        },
        firebase: {
            firebaseConnected: 'firebase-connected'
        },
        ui: {
            providerSelected: 'ui-provider-selected'
        }
    });

    /**
     * @ngdoc object
     * @name fvApp.constant:USER_ROLES
     * @description
     * # USER_ROLES
     * All the suported user roles
     */
    app.constant('USER_ROLES', {
        all: '*',
        admin: 'admin',
        user: 'user',
        guest: 'guest'
    });

    /**
     * @ngdoc Object
     * @name fvApp.constant:PATHS
     * @description
     * # PATHS
     * Rest paths
     */
    app.constant('PATHS', {
        root: 'https://futurvention.azurewebsites.net/',
        registration: 'https://futurvention.azurewebsites.net/Account/Register',
        public: 'https://futurvention.azurewebsites.net/public.svc/'
    });

    app.constant('EMBEDLY', {
        key: '05b548d0a515404f8f3da52d93eb402f',
        domain: 'http://api.embed.ly/1/',
        oembedAPI: 'oembed'
    });

    app.constant('SERVICE_CATALOGUE', [
        {
            Category: 'Design',
            Subcategory: 'Branding & Identity',
            Title: 'Logo Design',
            Description: [
                '<p>Overview of the service</p>',
                '<ul>',
                '<li>Up to 3 original and unique initial design concepts</li>',
                '<li>Unlimited revisions and color options until your approval of design</li>',
                '<li>100% original vector logo, scalable to any size without losing quality</li>',
                '<li>Full copyright ownership of the final artwork</li>',
                '</ul>',
                '<p>What you are expected to deliver</p>',
                '<ul>',
                '<li>Full logo package for the web display or printing including</li>',
                '<li>psd/ai source</li>',
                '<li>fonts used</li>',
                '<li>up to 2 of the following formats: .PSD .PNG .PDF .EPS .JPG</li>',
                '</ul>'
            ].join(''),
            Portfolio_formats: 'Image, richmedia, video\n',
            interview: 'optional',
            questions: [
            '<li>What work have you done in the past that proves your expertise?</li>',
            '<li>What are your key strengths in logo design that makes you stand out above other sellers?</li>',
            '<li>Why should the buyer trust you to deliver quality work?</li>'
            ].join(''),
            ServiceFields: [
                {
                    sellerTitle: '',
                    sellerDescription: '',
                    isRequired: '',
                    mediumCategory: '',
                }
            ],
            ServiceOptions: [
                {
                    isOptional: false,
                    isPriceDiscriminator: true,
                    name: '500 words'
                },
                {
                    isOptional: false,
                    isPriceDiscriminator: true,
                    name: '1000 words'
                },
                {
                    isOptional: false,
                    isPriceDiscriminator: true,
                    name: '2000 words'
                },
                {
                    isOptional: true,
                    isPriceDiscriminator: true,
                    name: 'Unlimited revisions'
                },
                {
                    isOptional: true,
                    isPriceDiscriminator: true,
                    name: 'Publish in Pr2 + blog'
                },
            ]
        },
        {
            'Category':'Design',
            'Subcategory':'Branding & Identity',
            'Title':'Logo Conversion to Vector',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Image, richmedia, video\n',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Logo conversion'
        },
        {
            'Category':'Design',
            'Subcategory':'Branding & Identity',
            'Title':'3D Logo Reveal/ Animation',
            'Price Discriminator':'',
            'Simple Addon':'1',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Video',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'3D Logo'
        },
        {
            'Category':'Design',
            'Subcategory':'Branding & Identity',
            'Title':'Business card',
            'Price Discriminator':'Number of concepts: 1,3',
            'Simple Addon':'1',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Image, richmedia, video\n',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Business card'
        },
        {
            'Category':'Design',
            'Subcategory':'Branding & Identity',
            'Title':'Stationary pack (business card, envelope, compliments slip, favicon)',
            'Price Discriminator':'Number of concepts: 1,3',
            'Simple Addon':'1',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Image, richmedia, video\n',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Stationary pack'
        },
        {
            'Category':'Design',
            'Subcategory':'Branding & Identity',
            'Title':'Custom brand identity design',
            'Price Discriminator':'Number of hrs:5, 10, 15, 30??',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Image, richmedia, video\n',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Design',
            'Subcategory':'Marketing',
            'Title':'Whiteboard doodle animation',
            'Price Discriminator':'Content: Simple video, Video + script writing, Video + voiceover, Video + script +voiceover',
            'Simple Addon':'1',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'video',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Doodle animation'
        },
        {
            'Category':'Design',
            'Subcategory':'Marketing',
            'Title':'Flyer/ Poster/ Leaflet Design',
            'Price Discriminator':'Number of sides:\n Single side, Two sides',
            'Simple Addon':'1',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'image, richmedia, video',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Flyer/ Poster'
        },
        {
            'Category':'Design',
            'Subcategory':'Marketing',
            'Title':'Brochure design',
            'Price Discriminator':'Number of pages:\n 4,6,8,12,16,trifold',
            'Simple Addon':'',
            'Internal Quantity (ND)':'1',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'image, richmedia, video',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Brochure'
        },
        {
            'Category':'Design',
            'Subcategory':'Marketing',
            'Title':'Infographic design',
            'Price Discriminator':'Number of items',
            'Simple Addon':'',
            'Internal Quantity (ND)':'1',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'image, richmedia, video',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Infographic'
        },
        {
            'Category':'Design',
            'Subcategory':'Marketing',
            'Title':'Website Illustration',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'image, richmedia, video',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':0,
            'Review':'',
            'Short Name':'Illustration'
        },
        {
            'Category':'Design',
            'Subcategory':'Marketing',
            'Title':'Powerpoint template design',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Richmedia, video, image, ppt, pptx',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Powerpoint template'
        },
        {
            'Category':'Design',
            'Subcategory':'Marketing',
            'Title':'Prezi Presentation',
            'Price Discriminator':'Number of slides: 10,20,30',
            'Simple Addon':'',
            'Internal Quantity (ND)':'1',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Prezi'
        },
        {
            'Category':'Design',
            'Subcategory':'Other',
            'Title':'Image editing',
            'Price Discriminator':'Number of images',
            'Simple Addon':'1',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'1',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Design',
            'Subcategory':'Other',
            'Title':'Custom graphic design',
            'Price Discriminator':'Number of hrs',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Design',
            'Subcategory':'Website/ app design',
            'Title':'Responsive homepage design',
            'Price Discriminator':'',
            'Simple Addon':'1',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'image, richmedia, video, url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Responsive website'
        },
        {
            'Category':'Design',
            'Subcategory':'Website/ app design',
            'Title':'Responsive Website design',
            'Price Discriminator':'Number of pages: 3,5,10',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'1',
            'External Quantity':'',
            'Portfolio formats':'image, richmedia, video, url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Design',
            'Subcategory':'Website/ app design',
            'Title':'Responsive Email newsletter design and code',
            'Price Discriminator':'Deliverable:\nnewsletter design + html code,\nnewsletter design + mailchimp ready code\nnewsletter design + campaign monitor ready code\nOnly newsletter design',
            'Simple Addon':'1',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'image, richmedia, video',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Responsive newsletter'
        },
        {
            'Category':'Design',
            'Subcategory':'Website/ app design',
            'Title':'Facebook/ Twitter page design',
            'Price Discriminator':'Target social network:\n twitter, facebook, twitter and facebook',
            'Simple Addon':'1',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'image, richmedia, video, url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Facebook cover'
        },
        {
            'Category':'Design',
            'Subcategory':'Website/ app design',
            'Title':'Mobile app design',
            'Price Discriminator':'Number of screens: 3,5,10',
            'Simple Addon':'',
            'Internal Quantity (ND)':'1',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'image, richmedia, video',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'Platform: android, iphone',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Design',
            'Subcategory':'Website/ app design',
            'Title':'Standard Banner',
            'Price Discriminator':'Number of different sizes:1,3,5,10',
            'Simple Addon':'',
            'Internal Quantity (ND)':'1',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'image, richmedia, video',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Standard Banner'
        },
        {
            'Category':'Design',
            'Subcategory':'Website/ app design',
            'Title':'Flash banner',
            'Price Discriminator':'Number of different sizes:1,3,5,10',
            'Simple Addon':'',
            'Internal Quantity (ND)':'1',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'richmedia, video',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Flash Banner'
        },
        {
            'Category':'Design',
            'Subcategory':'Website/ app design',
            'Title':'Animated Gif banner',
            'Price Discriminator':'Number of different sizes:1,3,5,10',
            'Simple Addon':'',
            'Internal Quantity (ND)':'1',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'image, richmedia, video',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Animated Gif'
        },
        {
            'Category':'Design',
            'Subcategory':'Website/ app design',
            'Title':'Icon set design',
            'Price Discriminator':'Number of icons:\n 5,10,15,30',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'image, richmedia, video',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Icon set'
        },
        {
            'Category':'Design',
            'Subcategory':'Website/ app design',
            'Title':'App Icon design',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'image, richmedia, video',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'App Icon'
        },
        {
            'Category':'Design',
            'Subcategory':'Website/ app design',
            'Title':'User/ usability testing',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'1',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':'Usability testing'
        },
        {
            'Category':'Design',
            'Subcategory':'Website/ app design',
            'Title':'Custom web design service',
            'Price Discriminator':'Number of hrs',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'image, richmedia, video, url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'Adwords',
            'Title':'Google Adwords Audit',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'1',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'Adwords',
            'Title':'Google Adwords account setup',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'1',
            'Seller Spec Amendment':'Do you offer any free credit/ Adwords Voucher and under what conditions?',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'Content distribution',
            'Title':'PR distribution',
            'Price Discriminator':'',
            'Simple Addon':'1',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'Where and how will be distributed',
            'Seller Constraints':'Area: UK, US, Rest of the world',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'Content distribution',
            'Title':'Article/ blog publication/ distribution',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'Where and how will be distributed',
            'Seller Constraints':'',
            'Speced':0,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'Content distribution',
            'Title':'Infographic distribution',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'Where and how will be distributed',
            'Seller Constraints':'',
            'Speced':0,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'Content distribution',
            'Title':'Video distribution',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'Where and how will be distributed',
            'Seller Constraints':'',
            'Speced':0,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'Leads/ Sales',
            'Title':'Email database/ list',
            'Price Discriminator':'Number of contacts: 50K, 100K, 500K, 1mln',
            'Simple Addon':'',
            'Internal Quantity (ND)':'1',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'Area: UK, US, Rest of the world',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'Leads/ Sales',
            'Title':'Targeted business email addresses for lead generation',
            'Price Discriminator':'Number of contacts: 50, 100, 500, 1000',
            'Simple Addon':'',
            'Internal Quantity (ND)':'1',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'Area: UK, US, Rest of the world',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'Leads/ Sales',
            'Title':'Telemarketing/ sales calls',
            'Price Discriminator':'Number of calls: 25,50,100,200',
            'Simple Addon':'',
            'Internal Quantity (ND)':'1',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'Other',
            'Title':'1 hr of web research',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':0,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'SEO',
            'Title':'Submit business details to top local citation sites',
            'Price Discriminator':'Number of citations',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'Where and how will be distributed',
            'Seller Constraints':'Area: UK, US, Rest of the world',
            'Speced':0,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'SEO',
            'Title':'Google Local and Map Citations for SEO Link Building\n',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'SEO',
            'Title':'Create your wikipedia page',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'SEO',
            'Title':'Business/ Company reviews',
            'Price Discriminator':'Number of reviews',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'Target site: Trustpilot, reviewcenter, yelp, google',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'SEo',
            'Title':'Appstore or GooglePlay App Reviews',
            'Price Discriminator':'Number of reviews',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'Appstore, GooglePlay',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'SEO',
            'Title':'Social bookmarking',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'Which sites to get backlinks from',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'SEO',
            'Title':'SEO Backlinks from PR9+ domains',
            'Price Discriminator':'Number of links',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'Which sites to get backlinks from',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'SEO',
            'Title':'Create .EDU and .GOV SEO Backlinks',
            'Price Discriminator':'Number of links',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'Which sites to get backlinks from',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'SEO',
            'Title':'UK/US local website Backlinks',
            'Price Discriminator':'Number of links',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'Which sites to get backlinks from',
            'Seller Constraints':'',
            'Speced':0,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'SEO',
            'Title':'Link Wheel',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'Seller to describe exactly what they offer and how it works',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'Might be penalized by google',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'SEO',
            'Title':'Keyword research',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'SEO',
            'Title':'Full SEO Link building package',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'Seller has to describe what they offer',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'SEO',
            'Title':'SEO Audit with keyword and competitor analysis',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'Seller spec amendment',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'Social media',
            'Title':'Manage Twitter/ Facebook pages',
            'Price Discriminator':'Number of weeks: 1 wk, 2 wks, 1 month\n',
            'Simple Addon':'',
            'Internal Quantity (ND)':'1',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Sales/ Marketing',
            'Subcategory':'Social media',
            'Title':'Facebook likes/ twitter followers/ subscribers/ fans etc',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'This is spam. Seriously think if we will use it',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Custom',
            'Title':'PSD to HTML/CSS',
            'Price Discriminator':'Number of pages: 1,3,5,10',
            'Simple Addon':'',
            'Internal Quantity (ND)':'1',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Custom',
            'Title':'PSD To responsive email',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Custom',
            'Title':'Website design and html/css conversion',
            'Price Discriminator':'Number of pages: 1,3,5,10',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':0,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Drupal',
            'Title':'Drupal theme customization',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Drupal',
            'Title':'PSD to Drupal theme',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Drupal',
            'Title':'Drupal theme setup',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Drupal',
            'Title':'Custom Drupal support/ consulting (incl. phone support)',
            'Price Discriminator':'Number of hrs\n 4,8,16',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Fixes',
            'Title':'PHP Error Fix',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Fixes',
            'Title':'HTML/ CSS Error Fix',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Fixes',
            'Title':'MySql Fix',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Fixes',
            'Title':'Javascript Fix',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Joomla',
            'Title':'Joomla Customization',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Joomla',
            'Title':'Joomla Problem/Error/ Bug Fix',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Joomla',
            'Title':'PSD or html to Joomla template',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Joomla',
            'Title':'Joomla Site Setup',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Joomla',
            'Title':'Custom Joomla support/ consulting (incl. phone support)',
            'Price Discriminator':'Number of hrs\n 4,8,16',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Magento',
            'Title':'PSD To Magento',
            'Price Discriminator':'Number of pages\n #6 pages (homepage + 5 inner pages)\n #10 pages (homepage + 9 inner pages)\n #1 custom page',
            'Simple Addon':'',
            'Internal Quantity (ND)':'1',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Magento',
            'Title':'Magento theme customization/ Create your online store with magento',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Magento',
            'Title':'Magento theme installation',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Magento',
            'Title':'Custom Magento support/ consulting (incl. phone support)',
            'Price Discriminator':'Number of hrs\n 4,8,16',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Magento',
            'Title':'Magento Speed/ performance optimization',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':0,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Magento',
            'Title':'Payment gateway installation and configuration',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Magento',
            'Title':'Magento error/ problem fix',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Magento',
            'Title':'Product entry on Magento eCommerce site',
            'Price Discriminator':'Number of products\n 10,50,100',
            'Simple Addon':'',
            'Internal Quantity (ND)':'1',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Opencart',
            'Title':'PSD To Opencart',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':0,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Opencart',
            'Title':'Opencart store setup',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Opencart',
            'Title':'Opencart theme installation',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':0,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Opencart',
            'Title':'Custom Opencart support/ consulting (incl. phone support)',
            'Price Discriminator':'Number of hrs\n 4,8,16',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'OpenCart',
            'Title':'Opencart Problem/Error/ Bug Fix',
            'Price Discriminator':'Number of fixes',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'OpenCart',
            'Title':'Product entry on opencart site',
            'Price Discriminator':'Number of products\n 10,50,100',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Other',
            'Title':'Setup Google analytics',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Prestashop',
            'Title':'PSD to Prestashop',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Prestashop',
            'Title':'Prestashop theme customization/ Create your online store with Prestashop',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Prestashop',
            'Title':'Custom Prestashop support/ consulting (incl. phone support)',
            'Price Discriminator':'Number of hrs\n 4,8,16',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Shopify',
            'Title':'PSD to Shopify',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Shopify',
            'Title':'Shopify theme customization/ Create your online store with Shopify',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Shopify',
            'Title':'Custom Shopify support/ consulting (incl. phone support)',
            'Price Discriminator':'Number of hrs\n 4,8,16',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Social',
            'Title':'Turn your website into a facebook app',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Tumblr',
            'Title':'Tumblr Tweeks',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Tumblr',
            'Title':'Tumblr blog setup',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Tumblr',
            'Title':'Provide Pr2+ tumblr account',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Wordpress',
            'Title':'PSD to Wordpress',
            'Price Discriminator':'Number of pages\n #5 pages (homepage + 4 inner pages)\n #1 custom page',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Wordpress',
            'Title':'Wordpress Customization',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Wordpress',
            'Title':'Wordpress setup',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Wordpress',
            'Title':'Wordpress Problem/Error/ Bug Fix',
            'Price Discriminator':'Number of fixes',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Wordpress',
            'Title':'Custom wordpress support/ consulting (incl. phone support)',
            'Price Discriminator':'Number of hrs\n 4,8,16',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Wordpress',
            'Title':'Wordpress site migration to new host',
            'Price Discriminator':'Site size\n #Small site (<500MB)\n #Big site (>500MB)',
            'Simple Addon':'1',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Wordpress',
            'Title':'Woocomerce installation and configuration',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Wordpress',
            'Title':'Product entry on Wordpress eCommerce shop/ Woocommerce',
            'Price Discriminator':'Number of products\n 10,50,100',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Wordpress',
            'Title':'Wordpress security and hardening',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Wordpress',
            'Title':'Recover and clean hacked Wordpress website',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Wordpress',
            'Title':'Wordpress plugin installation and configuration',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Wordpress',
            'Title':'Wordpress Speed/ Performance optimization',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Wordpress',
            'Title':'Wordpress SEO Optimization',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'Guided interview',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Wordpress',
            'Title':'Html to Wordpress theme',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Web Development',
            'Subcategory':'Wordpress',
            'Title':'Wordpress training',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'Guided interview',
            'Seller Spec Amendment':'Describe what the training consists of',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'CV',
            'Title':'CV Writing',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Image, doc',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'CV',
            'Title':'Cover letter',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Image, doc',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'CV',
            'Title':'LinkedIn profile',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Url, image',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'Other',
            'Title':'Voice over/ Video Script',
            'Price Discriminator':'Script duration: 30,60,90 secs',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Video, richmedia, audio, doc',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'Other',
            'Title':'Press release (writing and distribution)',
            'Price Discriminator':'Publishing: just writing, writing and publish',
            'Simple Addon':'',
            'Internal Quantity (ND)':'1',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Image, richmedia, doc, url',
            'Interview video':'',
            'Seller Spec Amendment':'Where press release will be published',
            'Seller Constraints':'Topic',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'Other',
            'Title':'Name, tagline or slogan for your product, service or business',
            'Price Discriminator':'number of names ',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Doc, image, richmedia',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'Other',
            'Title':'Sales Letter',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Image, richmedia, doc',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'Topic',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'Other',
            'Title':'Copywriting services',
            'Price Discriminator':'Worload: 2hrs, 3 hrs, 5 hrs, 8 hrs, 500 words, 1000 words, 2000 words',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Image, richmedia, doc, url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'Topic',
            'Speced':2,
            'Review':'This is general for the category if you need something custom ',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'Social',
            'Title':'Facebook Posts (Write and Schedule)',
            'Price Discriminator':'Number of posts: 10,30,50',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Image, richmedia, url, doc',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'Social',
            'Title':'Tweets (write and schedule)',
            'Price Discriminator':'Number of tweets:10,30,50',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Image, richmedia, url, doc',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'Translation',
            'Title':'Translation',
            'Price Discriminator':'Number of words: 250, 500, 1000, 2000',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'??? Does it make sense to upload translated documents?',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'Language pairs\nTopic',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'Web Content',
            'Title':'Product Descriptions',
            'Price Discriminator':'Number of descriptions: 5,10,20,50,100',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Richmedia, video, image, doc, url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'Topic',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'Web Content',
            'Title':'Email/ newsletter',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Doc, Image, Richmedia, video',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'Topic',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'Web Content',
            'Title':'Website Content (homepage, about me/ us page)',
            'Price Discriminator':'Page type:\n#General page\n#Homepage/ Landing page\n#About me/ us page\'\n',
            'Simple Addon':'1',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'Richmedia, image, doc, url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'Topic',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'Web Content',
            'Title':'Blog Post',
            'Price Discriminator':'Publishing: just writing, writing and publish',
            'Simple Addon':'1',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'1',
            'External Quantity':'',
            'Portfolio formats':'Richmedia, image, doc, url',
            'Interview video':'',
            'Seller Spec Amendment':'Where blog post will be published',
            'Seller Constraints':'Topic',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'Web Content',
            'Title':'(SEO) Article',
            'Price Discriminator':'Number of words:\n 300, 500, 1000',
            'Simple Addon':'1',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'1',
            'External Quantity':'',
            'Portfolio formats':'Richmedia, image, doc, url',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'Topic',
            'Speced':1,
            'Review':'Distribution should be by default part of the SEO article???',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'',
            'Title':'Telemarketing script',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'Topic',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'Other',
            'Title':'T&Cs/ Privacy policy',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'Other',
            'Title':'Data entry',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Writing',
            'Subcategory':'Other',
            'Title':'Proofreading',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Business support',
            'Subcategory':'',
            'Title':'Trascription',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Business support',
            'Subcategory':'',
            'Title':'Product Images',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':2,
            'Review':'',
            'Short Name':''
        },
        {
            'Category':'Business support',
            'Subcategory':'',
            'Title':'Data scraper',
            'Price Discriminator':'',
            'Simple Addon':'',
            'Internal Quantity (ND)':'',
            'Internal Quantity (D)':'',
            'External Quantity':'',
            'Portfolio formats':'',
            'Interview video':'',
            'Seller Spec Amendment':'',
            'Seller Constraints':'',
            'Speced':1,
            'Review':'',
            'Short Name':''
        }
    ]);
}());
